Develop
ofdun/bashnya_dz2 pull request #1
Opened 2023-11-20 21:25 UTC by ofdun

2023-11-28 18:32 UTC, Yu-Leo requested changes
Это первичное (архитектурное) ревью; в тонкости решения решения пока не вникал.

Видел твои вопросы про архитектуру проекта в комментариях. Действительно, одна из целей этой домашки - научиться выстраивать структуру (архитектуру) проекта.

Твой вариант неплох, но на мой взгляд тут явно напрашивается выделение "бизнес-логики" (логики унификации строк) в отдельный пакет.

Я предлагаю следующий вариант разбиения на пакеты со своими зонами ответственности:
1. Парсинг флагов и аргументов командной строки
2. "Бизнес-логика" - уникализация набора строк в зависимости от параметров
3. Чтение строк из stdin/файла
4. Запись строк в stdout/файл
5. main файл в корне репозитория, в котором "связываются" все пакеты

3 и 4 пункты можно объединить в один пакет

В main должно быть буквально:
1. Парсинг флагов и аргументов (вызов ф-ции из пакета 1)
2. Чтение строк (вызов ф-ции из пакета 3)
3. Обработка строк с учетом флагов (вызов ф-ции из пакета 2)
4. Вывод строк (вызов ф-ции из пакета 4)

Исправь структуру проекта в соответствии с этим разбиением и поправь небольшие замечания, которые сейчас указал (как сделаешь, напиши тут "ИСПРАВЛЕНО", чтобы я видел, что можно ещё раз посмотреть твое решение). После этого буду более детально смотреть, что можно поправить

P.S. За тесты респект!

2023-11-28 18:32 UTC, Yu-Leo commented on acceptance-tests/tests.sh
> +echo -e "\e[32mSUMMARY   : SUCCESS\e[0m"
Что тут поменялось?

2023-11-28 18:32 UTC, Yu-Leo commented on actions/actions.go
> +func Output(opt settings.Options, output []string) error {
Тут можно использовать интерфейс `io.Writer`, чтобы обощить вывод в stdout и в файл

2023-11-28 18:32 UTC, Yu-Leo commented on actions/actions.go
> +func Input(opt settings.Options) ([]string, error) {
Тут можно использовать интерфейс `io.Reader`, чтобы обощить вывод в stdout и в файл

2023-11-28 18:32 UTC, Yu-Leo commented on settings/options.go
> +	//return initOptions(c, d, u, *skipfPtr, *skipCPtr, *ignorePtr), nil
Закоментированный код можно и нужно удалить

2023-11-28 18:32 UTC, Yu-Leo commented on settings/options.go
> +}
Думаю, лучше разделить флаги командной строки и логику ввода-вывода (имена файлов и т д) на две структуры

2023-11-28 18:32 UTC, Yu-Leo commented on settings/options.go
> +package settings
Странно, что пакет называется "settings", а файл в нем - "options". Сбивает с толку. Думаю, лучше назвать одинаково

2023-12-10 18:25 UTC, ofdun commented
ИСПРАВЛЕНО

2023-12-16 16:36 UTC, Yu-Leo approved these changes
**Аппрув! 🎆**

ДЗ принято.

Пару небольших замечаний оставил, поправь и можешь смерджить ветки.

Ещё раз респект за тесты) 🔥

2023-12-16 16:36 UTC, Yu-Leo commented on actions/actions.go
> +package actions
Из названия пакета не понятно, что в нём находится. Думаю, лучше переименовать в `unification` или просто `uniq`, чтобы было понятно

2023-12-16 16:36 UTC, Yu-Leo commented on actions/actions.go
> +	"uniq/m/options"
Между дефолтными либами и внутренними пакетами проекта принято оставлять пустую строку

2023-12-20 13:35 UTC, merged